### ISSUE TITLE
server watchdog shutting server down after tick takes 60+ seconds 

### ISSUE THREAD

**Issue by Ajw2003** [TeamDeusVult/KoTRT_Core#2]
running does it tick 2.0.0.0 and other mods yes, however, the number of times does it tick mixins and chunk loading techniques are mentioned in this crash report leads me to believe it is an issue with this mod and not another, or at least an interaction between it and another mod.
[crash-2022-01-13_15.19.45-server.txt](https://github.com/TeamDeusVult/KoTRT_Core/files/7866589/crash-2022-01-13_15.19.45-server.txt)

if you need anymore details please let me know, I love the utility of your mod, just don't love it crashing lol

**Comment by WFPhantom** [comment]
Does it happen without the mod? It's a common thing happening on modded servers. Increasing the tick time in server properties should fix it.

**Comment by txnitxnichopper** [comment]
Nothing to do with my mod. 

For future reference, the callstack format is `at package.Class.method() {mixin list for that entire class}`, it is far more important where the crash is coming from than which mods have mixins. I have a mixin in `ServerChunkProvider`, yes, but not even on this method.

This appears to be something fucked with either ImmersiveFX or ZombieAwareness doing some multithreading that they shouldn't. Don't have time to debug someone else's crashlog, take it up with them.

**Comment by Ajw2003** [comment]
Yeah sorry about that, Looked more into the crash report and found that those two mods together caused an issue when certain mobs were spawned :/ my bad
