### ISSUE TITLE
Hostile mobs do not spawn naturally when this mod and Performant installed

### ISSUE THREAD

**Issue by Wizych** [TeamDeusVult/KoTRT_Core#3]
Hello!When i create and join the world hostile mobs do not spawn naturally, even at night and with normal difficulty.They only spawn with spawners.But when i use either mod they spawn normally.I have only Does it tick and Performant installed in my modpack.Does it tick version - does_it_tick-1.16.5_v2.0.0.jar, Performant is - performant-1.16.2-5-3.84m.jar.
With Does it tick installed:
![2022-02-06_20 11 46](https://user-images.githubusercontent.com/92752758/152693650-d9c468a2-7d46-46a3-a6c0-8fd32f7668c8.png)
With Does it tick and Performant installed:
![2022-02-06_20 16 24](https://user-images.githubusercontent.com/92752758/152693686-e464f68a-5fb8-4ab7-acc2-3d1dc151becc.png)

**Comment by WFPhantom** [comment]
Performant does cause issues and breaks a lot of things. It's a closed source performance mod. Does it happen without performant?

**Comment by Wizych** [comment]
> Performant does cause issues and breaks a lot of things. It's a closed source performance mod. Does it happen without performant?
No,its not happening

**Comment by Wizych** [comment]
> Performant does cause issues and breaks a lot of things. It's a closed source performance mod. Does it happen without performant?

No,its not happening

**Comment by txnitxnichopper** [comment]
I'm not going to debug issues with Performant---its a closed source mod that breaks everything. The developer is an asshat and doesn't care about the issues with it or any of his other broken closed source mods. 

It's not that good anyway. You should uninstall it.

**Comment by devjavu7** [comment]
"It's not that good anyway" I would like you to back up that statement please

**Comment by txnitxnichopper** [comment]
This is a two month old closed issue, but it breaks tons of mods and doesn't improve performance by as much as it claims. Compared to better, safer mods like Lithium, there's no reason to install closed-source crap.
